version: "3.7"

services:
  vlx2mqtt:
    build: .
    image: python:buster
    command: python vlx2mqtt.py vlx2mqtt.cfg
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - my-net
    restart: always 

networks:
  my-net:
    driver: bridge
